allowBuilds:
  '@sentry/cli': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  supabase: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - ngrok
  - protobufjs
  - sharp
  - supabase
  - unrs-resolver
